BC: bc/*
feature: [feature/*, task/*]
fix: [fix/*, bug/*, bugfix/*]
refactoring: [refactor/*, refactoring/*]
documentation: [docs/*, documentation/*]
maintenance: maintenance/*
'skip changelog': release/*
