name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
exclude-labels:
  - 'skip changelog'
categories:
  - title: ⚠️ Breaking Changes
    label: BC
  - title: 🌟 Features
    labels:
      - feature
      - enhancement
  - title: 🐞 Bug Fixes
    labels:
      - bug
      - bugfix
  - title: ♻️ Refactoring
    label: refactoring
  - title: 📖 Documentation
    label: documentation
  - title: 🔧 Maintenance
    label: maintenance
version-resolver:
  major:
    labels:
      - BC
  minor:
    labels:
      - feature
  patch:
    labels:
      - bug
      - bugfix
  default: patch
template: |
  $CHANGES
