# We freezed the version of mkdocs-material to prevent issue with live reload
# See <https://github.com/squidfunk/mkdocs-material/issues/8478>
FROM            squidfunk/mkdocs-material:9.6.20
RUN             mkdir /workspace
WORKDIR         /workspace
