import type { PropTests } from '../../../../../tests/playwright/types';

export const contentPropTest: PropTests = [
  {
    name: 'children:string=long',
    props: {
      children: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Sed ac dolor sit amet purus malesuada congue. Vivamus luctus egestas leo. Aenean fermentum risus id tortor. Pellentesque ipsum. Nunc auctor. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Mauris metus. Etiam dictum tincidunt diam. Etiam quis quam. Duis viverra diam non justo. Etiam bibendum elit eget erat. Vivamus porttitor turpis ac leo. Etiam quis quam. Phasellus faucibus molestie nisl. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Mauris elementum mauris vitae tortor. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Etiam commodo dui eget wisi. Integer malesuada. Suspendisse nisl. Nulla est. Proin in tellus sit amet nibh dignissim sagittis. Cras elementum. Praesent in mauris eu tortor porttitor accumsan. Praesent id justo in neque elementum ultrices. Fusce consectetuer risus a nunc. Duis risus. In convallis. Nulla non lectus sed nisl molestie malesuada. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Proin in tellus sit amet nibh dignissim sagittis. In convallis. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Nunc dapibus tortor vel mi dapibus sollicitudin. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. ',
    },
  },
];
