FROM        node:10

#######################
# Configure workspace #
#######################

RUN          mkdir /workspace

##############
# Copy files #
##############

COPY        ./init-container.sh /root/init-container.sh

###############################
# Configure working directory #
###############################

WORKDIR     /workspace
