name: External Links Check

on:
  pull_request:

jobs:
  broken_link_check:
    name: Markdown link check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.github/markdown-link-check.json'
          use-verbose-mode: 'yes'
