name: Lint

on: [ pull_request ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Print Node.js and npm version
        run: node --version && npm --version

      - name: Install
        run: npm ci

      - name: Test
        run: npm run lint
