name: Lint

on: [ pull_request ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # TODO: Add v18 back (#374) once the docs platform is migrated to a non-Gatsby solution (#373).
        # node: [ 16, 18 ]
        node: [ 16 ]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Print Node.js and npm version
        run: node --version && npm --version

      - name: Install
        run: npm ci

      - name: Test
        run: npm run lint
