name: Pull Request Meta

on:
  pull_request:
    types: [ opened ]

jobs:
  process_pr_meta:
    name: Process PR meta
    runs-on: ubuntu-24.04
    steps:
      - name: Assign to author
        uses: kentaro-m/auto-assign-action@v2.0.0 # Specify also the minor version because v2 does not exist

      - name: Add labels
        uses: TimonVS/pr-labeler-action@v5
        env:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
