name: Pull Request Meta

on:
  pull_request:
    types: [ opened ]

jobs:
  process_pr_meta:
    name: Process PR meta
    runs-on: ubuntu-20.04
    steps:
      - name: Assign to author
        uses: samspills/assign-pr-to-author@v1.0 # specify also the minor version because v1 does not exist
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add labels
        uses: TimonVS/pr-labeler-action@v4
        env:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
