name: Build and Run Tests

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [ 14, 15 ]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-node-v${{ matrix.node }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-node-v${{ matrix.node }}-${{ env.cache-name }}-
            ${{ runner.os }}-build-node-v${{ matrix.node }}-

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
