name: Build and Run Tests

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [ 12 ]

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/workflows/test.yml') }}
        restore-keys: |
          ${{ runner.OS }}-node-v${{ matrix.node }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/workflows/test.yml') }}
          ${{ runner.OS }}-node-v${{ matrix.node }}-

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test
