name: Test

on:
  pull_request:
  schedule:
    - cron: '0 6 * * *' # daily at 6:00 UTC (7:00 CET, 8:00 CEST)

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Print Node.js and npm version
        run: node --version && npm --version

      - name: Install
        run: npm ci

      - name: Test and generate code coverage info
        run: npm test

      - name: Upload code coverage info to Coveralls
        uses: coverallsapp/github-action@v2
